NGSimulator {
  seed = 100
  outputDirectory = "./output"
  NetModel {
    distanceSpreadThreshold = 0.05
    numberOfExperiments = 1
    perturbationCoefficient = 0.25
    dissimulationCoefficient = 0.12
    distanceCoefficient = 0.2
    edgeProbability = 0.015
    statesTotal = 200
    desiredReachabilityCoverage = 1.0
    numberOfWalks = 20
    maxBranchingFactor = 6
    maxDepth = 5
    maxProperties = 15
    propValueRange = 100
    actionType = 20
    actionRange = 10
    connectedness = 4
    maxWalkPathLengthCoeff = 2
    graphWalkTerminationPolicy = ${NGSimulator.Constants.MaxPathLength}
    graphWalkNodeTerminationProbability = 0.001d
    valuableDataProbability = 0.001d
  }
  CostRewards {
    malAppBudget = 1500.0
    costOfDetection = 0.2d
    serviceRewardProbability = 0.3
    serviceReward = 6d
    servicePenalty = 2d
    targetAppScore = 5
    targetAppLowPenalty = 1
    targetAppHighPenalty = 2
  }
  Constants {
    MaxPathLength  = "maxpathlength"
    UntilCycle = "untilcycle"
    All = "all"
  }
  Graph {
    directionality = "directed"
    fileName = "NetGameSimNetGraph_medium.ngs"
    outputPath = "./converted"
    graphLocation = "../../../"
  }
  OutputGraphRepresentation {
    contentType = "json"
  }
}
