NGSimulator {
  seed = 100
  outputDirectory = "./output"
  NetModel {
    distanceSpreadThreshold = 0.05
    numberOfExperiments = 1
    perturbationCoefficient = 0.2
    dissimulationCoefficient = 0.1
    distanceCoefficient = 0.2
    edgeProbability = 0.02
    statesTotal = 80
    desiredReachabilityCoverage = 1.0
    numberOfWalks = 10
    maxBranchingFactor = 5
    maxDepth = 4
    maxProperties = 10
    propValueRange = 50
    actionType = 10
    actionRange = 10
    connectedness = 3
    maxWalkPathLengthCoeff = 2
    graphWalkTerminationPolicy = ${NGSimulator.Constants.MaxPathLength}
    graphWalkNodeTerminationProbability = 0.001d
    valuableDataProbability = 0.001d
  }
  CostRewards {
    malAppBudget = 1000.0
    costOfDetection = 0.2d
    serviceRewardProbability = 0.3
    serviceReward = 5d
    servicePenalty = 2d
    targetAppScore = 5
    targetAppLowPenalty = 1
    targetAppHighPenalty = 2
  }
  Constants {
    MaxPathLength  = "maxpathlength"
    UntilCycle = "untilcycle"
    All = "all"
  }
  Graph {
    directionality = "directed"
    fileName = "NetGameSimNetGraph_small.ngs"
    outputPath = "./converted"
    graphLocation = "../../../"
  }
  OutputGraphRepresentation {
    contentType = "json"
  }
}
